[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              ${MINI_DROP_LOG_PATHS}
    Tag               mini_drop.logs
    Refresh_Interval  5
    Rotate_Wait       30
    Mem_Buf_Limit     10MB
    Skip_Long_Lines   On
    DB                /buffers/fluent-bit-state.db
    Parser            docker_or_plain

[INPUT]
    Name              systemd
    Tag               mini_drop.systemd
    Path              /var/log/journal
    DB                /buffers/fluent-bit-systemd-state.db
    Read_From_Tail    On
    Strip_Underscores Off

[OUTPUT]
    Name   file
    Match  mini_drop.logs
    Path   /buffers
    File   logs.ndjson
    Format plain

[OUTPUT]
    Name   file
    Match  mini_drop.systemd
    Path   /buffers
    File   systemd.ndjson
    Format plain
